version: '3.8'

services:
  postgres-database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-details
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - elk

  api-node-1:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-details
    ports:
      - "8000:8000"
    depends_on:
      - postgres-database
      - pgadmin
    networks:
      - elk
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100m
        reservations: 
          cpus: '0.5'
          memory: 10m

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres-database
    ports:
      - "5050:80"
    networks:
      - elk
  
networks:

  elk:
    driver: bridge